name: CI

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: nrwl/nx-set-shas@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        cache: "yarn"
        node-version: "18.16.0"

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - run: git branch --track master origin/master

    - run: npx nx format:check
    - run: npx nx affected -t lint --parallel=3
    - run: npx nx affected -t test --parallel=3
    - run: npx nx affected -t build --parallel=3
      
