name: Prerelease

on:
  push:
    branches:
      - alpha
      - beta
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'

      - name: Configure Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - run: yarn nx affected -t lint --parallel=3
      - run: yarn nx affected -t test --parallel=3
      - run: yarn nx affected -t build --parallel=3

      - name: Release
        run: yarn nx affected -t version -c ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: yarn nx affected -t deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
